<!-- wp:sgb/box {"boxClassName":"box3","css":".sng-box {\n    border-radius: var(\u002d\u002dwp\u002d\u002dcustom\u002d\u002drounded\u002d\u002dmedium,8px);\n\ttext-align: center;\n}\n\n.cta-btn__title {\n    display: inline-block;\n    position: relative;\n    padding: 0 25px;\n    line-height: 1;\n    letter-spacing: 1px;\n}\n\n.cta-btn__title:before {\n    left: 0;\n    -webkit-transform: rotate(50deg);\n    transform: rotate(50deg);\n}\n\n.cta-btn__title:after, .cta-btn__title:before {\n    display: inline-block;\n    position: absolute;\n    top: 50%;\n    width: 20px;\n    height: 3px;\n    border-radius: 3px;\n    background-color: #d8dae1;\n    content: \u0022\u0022;\n}\n\n.cta-btn__title:after {\n    right: 0;\n    -webkit-transform: rotate(-50deg);\n    transform: rotate(-50deg);\n}","scopedCSS":"#id-c69432ad-d0fe-4fbe-a090-ca08730e6edc .sng-box {\n    border-radius: var(\u002d\u002dwp\u002d\u002dcustom\u002d\u002drounded\u002d\u002dmedium,8px);\n\ttext-align: center;\n}\n\n#id-c69432ad-d0fe-4fbe-a090-ca08730e6edc .cta-btn__title {\n    display: inline-block;\n    position: relative;\n    padding: 0 25px;\n    line-height: 1;\n    letter-spacing: 1px;\n}\n\n#id-c69432ad-d0fe-4fbe-a090-ca08730e6edc .cta-btn__title:before {\n    left: 0;\n    -webkit-transform: rotate(50deg);\n    transform: rotate(50deg);\n}\n\n#id-c69432ad-d0fe-4fbe-a090-ca08730e6edc .cta-btn__title:after,#id-c69432ad-d0fe-4fbe-a090-ca08730e6edc  .cta-btn__title:before {\n    display: inline-block;\n    position: absolute;\n    top: 50%;\n    width: 20px;\n    height: 3px;\n    border-radius: 3px;\n    background-color: #d8dae1;\n    content: \u0022\u0022;\n}\n\n#id-c69432ad-d0fe-4fbe-a090-ca08730e6edc .cta-btn__title:after {\n    right: 0;\n    -webkit-transform: rotate(-50deg);\n    transform: rotate(-50deg);\n}","blockId":"id-c69432ad-d0fe-4fbe-a090-ca08730e6edc"} -->
<div class="wp-block-sgb-box sng-box box3">
  <!-- wp:paragraph {"align":"center","textColor":"sango_gray","className":"cta-btn__title","fontSize":"medium","blockId":"id-49ee556a-0dff-4d87-8e0f-dfcdf2242200"} -->
  <p class="has-text-align-center cta-btn__title has-sango-gray-color has-text-color has-medium-font-size">24時間予約受付中</p>
  <!-- /wp:paragraph -->

  <!-- wp:sgb/btn {"btnType":"cubic2","btnColor":"#5ba9f7","label":"このクリニックの予約空き状況を確認する","href":"<?php echo esc_url(generate_cta_url($clinic_data->cta)) ?>","align":"center","icon":"fas fa-angle-right","css":".btn{\n  border: 2px solid transparent;\n  position: relative;\n  overflow: hidden;\n}","scopedCSS":"#id-3eec9d68-292b-45ee-89d0-163da0d7e5ca .btn{\n  border: 2px solid transparent;\n  position: relative;\n  overflow: hidden;\n}","blockId":"id-3eec9d68-292b-45ee-89d0-163da0d7e5ca"} -->
  <p class="wp-block-sgb-btn sng-align-center"><a style="background-color:#5ba9f7" class="btn cubic2 shadow raised"
      href="<?php echo esc_url(generate_cta_url($clinic_data->cta)) ?>"><i class="fas fa-angle-right"></i>このクリニックの予約空き状況を確認する</a></p>
  <!-- /wp:sgb/btn -->
</div>
<!-- /wp:sgb/box -->